name: Daily Taipower Settlement Monthly Files

on:
  schedule:
    # UTC 01:30 = 台北 09:30（你也可以自己調）
    - cron: "30 1 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: daily-taipower
  cancel-in-progress: false

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compute today's date in Taipei
        id: dates
        run: |
          TODAY=$(TZ=Asia/Taipei date +%F)
          echo "today=$TODAY" >> $GITHUB_OUTPUT

      - name: Run monthly updater (CSV + JSON)
        run: |
          mkdir -p data
          python update_monthly_settlement.py --date "${{ steps.dates.outputs.today }}" --outdir data --fallback-yesterday

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add data/settlement_*.csv data/settlement_*.json

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "data: update monthly settlement files (${{ steps.dates.outputs.today }})"
          git push
